name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
